class protocol:
    SETUSERNAME =   "SETUSRNM"
    ACCEPT =        "ACCEPT__"
    REJECT =        "REJECT__"
    HELP =          "HELP____"
    CREATEROOM =    "CREATERM"
    GETROOMLIST =   "GETROOMS"
    ROOMLIST =      "LISTROOM"
    JOINROOM =      "JOINROOM"
    LEAVEROOM =     "EXITROOM"
    MESSAGE =       "MESSAGE_"
    UPDATE =        "UPDATE__"
    EXIT =          "EXIT____"